export const AUTH_ERROR_CODES = {
  INVALID_OR_EXPIRED_TOKEN: 'INVALID_OR_EXPIRED_TOKEN',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  INVITE_CODE_INVALID: 'INVITE_CODE_INVALID',
} as const

export const PASSWORD_RESET_TOKEN_EXPIRES_IN_HOURS = 1
