export const EMAIL_QUEUE_NAME = 'email-queue'
export const EMAIL_SEND_ATTEMPTS = 4
export const EMAIL_ERROR_CODES = {
  FAILED_TO_SEND: 'FAILED_TO_SEND',
  INVALID_PAYLOAD: 'INVALID_PAYLOAD',
  TRANSPORT_NOT_CONFIGURED: 'TRANSPORT_NOT_CONFIGURED',
  FAILED_TO_RENDER_TEMPLATE: 'FAILED_TO_RENDER_TEMPLATE',
} as const
