export const PROJECT_ERROR_CODES = {
  INVALID_SUBCATEGORIES_COUNT: 'INVALID_SUBCATEGORIES_COUNT',
  SUBCATEGORIES_NOT_FOUND: 'SUBCATEGORIES_NOT_FOUND',
  PROJECT_ARCHIVED: 'PROJECT_ARCHIVED',
} as const

export const MIN_SUBCATEGORIES = 1
export const MAX_SUBCATEGORIES = 20
